crud_project/base/urls.py
from django.urls import path

from crud_project.base.views import HomeTemplateView

app_name = 'base'
urlpatterns = [
    path('', HomeTemplateView.as_view(), name='home'),
]

crud_project/client/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path

from crud_project.client.views import ClientListView, ClientUpdateView, ClientDeleteView, ClientCreateView, \
    ClientDadosUpdateView

app_name = 'client'
urlpatterns = [
    path('clientes/', login_required(ClientListView.as_view()), name='lista_cliente'),
    path('clientes/atualiza/<slug:slug>', login_required(ClientUpdateView.as_view()), name='atualiza_cliente'),
    path('clientes/excluir/<slug:slug>', login_required(ClientDeleteView.as_view()), name='deleta_cliente'),
    path('clientes/cadastrar/', login_required(ClientCreateView.as_view()), name='cadastra_cliente'),
    path('clientes/<slug:slug>', login_required(ClientDadosUpdateView.as_view()), name='dados_cliente'),
]

crud_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('crud_project.base.urls')),
    path('', include('django.contrib.auth.urls')),
    path('', include('crud_project.client.urls')),
]

crud_project/base/models.py
from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
from django.contrib.auth.models import PermissionsMixin
from django.core.mail import send_mail
from django.db import models
from django.utils import timezone
from django.utils.translation import gettext_lazy as _


class UserManager(BaseUserManager):
    use_in_migration = True

    def _create_user(self, email, password, **extra_fields):
        """
        Creates and saves a User with the given email and password
        :param email:
        :param password:
        :param extra_fields:
        :return:
        """
        if not email:
            raise ValueError('The given email must be set')
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, password=None, **extra_fields):
        extra_fields.setdefault("is_superuser", False)
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email, password, **extra_fields):
        extra_fields.setdefault("is_superuser", True)
        extra_fields.setdefault("is_staff", True)

        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')
        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')

        return self._create_user(email, password, **extra_fields)


class User(AbstractBaseUser, PermissionsMixin):
    """
    App base user class

    Email and password are required. Other fields are optional.
    """

    first_name = models.CharField(_('first name'), max_length=150, blank=True)
    email = models.EmailField(_('email address'), unique=True)
    is_staff = models.BooleanField(
        _('staff status'),
        default=False,
        help_text=_('Designates whether the user can log into this admin site.'),
    )
    is_active = models.BooleanField(
        _('active'),
        default=True,
        help_text=_(
            'Designates whether this user should be treated as active. '
            'Unselect this instead of deleting accounts.'
        ),
    )
    date_joined = models.DateTimeField(_('date joined'), default=timezone.now)

    objects = UserManager()

    EMAIL_FIELD = 'email'
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    class Meta:
        verbose_name = _('user')
        verbose_name_plural = _('users')

    def clean(self):
        super().clean()
        self.email = self.__class__.objects.normalize_email(self.email)

    def get_full_name(self):
        """
        Return the first_name plus the last_name, with a space in between.
        """
        full_name = str(self.first_name)
        return full_name.strip()

    def get_short_name(self):
        """Return the short name for the user."""
        return self.first_name

    def email_user(self, subject, message, from_email=None, **kwargs):
        """Send an email to this user."""
        send_mail(subject, message, from_email, [self.email], **kwargs)

crud_project/client/models.py
from django.db import models

# Create your models here.
from django.template.defaultfilters import slugify
from django.urls import reverse


class Client(models.Model):
    nome = models.CharField(max_length=64)
    slug = models.SlugField(unique=True)
    endereco = models.TextField()
    telefone = models.CharField(max_length=15)
    data_nascimento = models.DateField()
    data_cadastro = models.DateTimeField(auto_now_add=True)

    def save(self, *args, **kwargs):
        # autocompleta o slug
        self.slug = slugify(self.nome)
        super(Client, self).save(*args, **kwargs)

    def __str__(self):
        return self.nome

    def get_absolute_url(self):
        # obtem o caminho do cliente
        return reverse('client:dados_cliente', kwargs={'slug': self.slug})

crud_project/client/forms.py
from django import forms

from crud_project.client.models import Client


# Cria o Formulário de acordo com o modelo
class InsereClientForm(forms.ModelForm):

    class Meta:
        model = Client
        fields = [
            'nome',
            'endereco',
            'telefone',
            'data_nascimento',
        ]

crud_project/base/views.py
from django.views.generic import TemplateView


class HomeTemplateView(TemplateView):
    template_name = "base/home.html"

crud_project/client/views.py
from django.urls import reverse_lazy
from django.views.generic import ListView, UpdateView, DeleteView, CreateView

from crud_project.client.forms import InsereClientForm
from crud_project.client.models import Client


# Lista os clientes cadastrados
class ClientListView(ListView):
    template_name = "client/lista.html"
    model = Client
    context_object_name = "cliente"


# Lista atualiza os dados cadastrais dos clientes
class ClientUpdateView(UpdateView):
    template_name = 'client/atualiza.html'
    model = Client
    fields = [
        'nome',
        'endereco',
        'telefone',
        'data_nascimento',
    ]


# Lista exclui cliente
class ClientDeleteView(DeleteView):
    template_name = 'client/exclui.html'
    model = Client
    context_object_name = 'cliente'
    success_url = reverse_lazy("client:lista_cliente")


# Lista cria cliente
class ClientCreateView(CreateView):
    template_name = "client/cria.html"
    model = Client
    form_class = InsereClientForm
    success_url = reverse_lazy("client:lista_cliente")


# detalhe dos dados de um cliente
class ClientDadosUpdateView(UpdateView):
    template_name = 'client/dados_cliente.html'
    model = Client
    fields = '__all__'
    context_object_name = 'client'

crud_project/base/templates/base/base.html
{% load static %}

<!DOCTYPE html>
<html lang="pt-br">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>{% block title %}CRUD-CLIENT{% endblock %}</title>

    <meta name="description" content="Página SeriesFlix">
    <meta name="author" content="Ravellys">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@600&display=swap" rel="stylesheet">

    <link rel="icon" type="image/png" href="{% static 'images/figura.png' %}" >
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/scripts.js' %}"></script>

  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <a class="navbar-brand" href="{% url 'base:home' %}">Home</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item">
           <a class="nav-link" href="{% url 'client:lista_cliente' %}">Lista Clientes</a>
          </li>
          <li class="nav-item">
          <a class="nav-link" href="{% url 'client:cadastra_cliente' %}">Cadastro de Clientes</a>
          </li>
        </ul>
      </div>
         {% if user.is_authenticated %}
            <ul class="navbar-nav">

                <li class="nav-item mt-2 mr-2">
                    <p class="nav-item text-white align-text-bottom">
                        Usuário: {{ user.first_name }}
                    </p>
                </li>
                <li class="nav-item">
                    <a class="btn btn-danger" href="{% url 'logout' %}">Sair</a>
                </li>

            </ul>

        {% else %}
            <a class="btn btn-light my-2" href="{% url 'login' %}">Entrar</a>
        {% endif %}
    </nav>

    {% block body %}{% endblock %}
    {% include 'base/footer.html'%}
  </body>
</html>

crud_project/base/templates/base/footer.html
<footer class="fixed-bottom mt-2 pt-1 text-white">


    <p>Copyright © {% now 'Y' %} - by
        <a href="https://ravellys.github.io"> Lucas Ravellys  </a>
    </p>
</footer>

crud_project/base/templates/base/home.html
{% extends 'base/base.html' %}
{% load static %}
{% block title %}Home{% endblock title %}


{% block body %}

    <main class="p-4 m-4" >
        <h1 class="p-4 m-4 text-white display-3 text-center">Bem Vindo</h1>
    </main>

{% endblock %}

crud_project/client/templates/client/atualiza.html
{% extends 'base/base.html' %}
{% load widget_tweaks %}
{% load static %}
{% block title %}Atualizar{% endblock title %}


{% block body %}
<div class="container">
    <div class="row">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 mt-2">
            <div class="card">
                <div class="card-body bg-dark">
                    <h5 class="card-title text-white">Atualização de Cliente</h5>
                    <p class="card-text text-white">
                    Complete o formulário abaixo para Atualizar
                    um novo <code>Cliente</code>.
                    </p>


                    <form method="post">
                        {% csrf_token %}

                        {% for field in form %}
                            <div class="input-group mb-3">
                                <div class="input-group-prepend">
                                    <span class="input-group-text">{{ field.label }}</span>
                                </div>
                            {% render_field field class+="form-control" %}
                            </div>
                        {% endfor %}

                        <button class="btn btn-primary">Enviar</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

crud_project/client/templates/client/cria.html
{% extends 'base/base.html' %}
{% load widget_tweaks %}
{% load static %}
{% block title %}Cadastrar{% endblock title %}


{% block body %}

<div class="container">
    <div class="row">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <div class="card">
                <div class="card-body bg-dark">

                    {% block titulo %}
                        <h5 class="card-title text-white">Cadastro de Cliente</h5>
                        <p class="card-text text-white">
                        Complete o formulário abaixo para cadastrar
                        um novo <code>Cliente</code>.
                        </p>
                    {% endblock %}


                    <form method="post">
                        {% csrf_token %}
                        {% for field in form %}
                            <div class="input-group mb-3">
                                <div class="input-group-prepend">
                                    <span class="input-group-text">{{ field.label }}</span>
                                </div>
                            {% for error in field.errors %}
                                <div class="bg-danger d-print-flex" role="alert">
                                    <p>{{ error }}</p>
                                </div>
                            {% endfor %}
                            {% render_field field class+="form-control" %}
                            </div>
                        {% endfor %}
                        <button class="btn btn-primary">Enviar</button>
                    </form>

                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

crud_project/client/templates/client/dados_cliente.html
{% extends 'base/base.html' %}
{% load widget_tweaks %}
{% load static %}
{% block title %}Dados do Cliente{% endblock title %}

{% block body %}

<div class="container d-block">
    <div class="row">
        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6 mt-2">
            <div class="card">
                <div class="card-body bg-dark">
                    <h3 class="text-white">{{ client.nome | default:"nothing" }}</h3>

                      <dl class="text-light">
                         <dt><code>Endereço:</code></dt>
                         <dd>{{ client.endereco }}</dd>
                      </dl>
                      <dl class="text-light">
                         <dt><code>Telefone:</code></dt>
                         <dd>{{ client.telefone }}</dd>
                      </dl>
                      <dl class="text-light">
                         <dt><code>Data de Nascimento:</code></dt>
                         <dd>{{ client.data_nascimento }}</dd>
                      </dl>
                      <dl class="text-light">
                         <dt><code>Data de Cadastro:</code></dt>
                         <dd>{{ client.data_cadastro }}</dd>
                      </dl>
                </div>
            </div>
        </div>
    </div>
 </div>
{% endblock %}

crud_project/client/templates/client/exclui.html
{% extends 'base/base.html' %}
{% load static %}
{% block title %}Excluir{% endblock title %}


{% block body %}

<div class="container d-block">
    <div class="row">
        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6 mt-2">
            <div class="card">
                <div class="card-body bg-dark text-light">
                    <main class="p-4 m-4" >
                        <h1 class="p-4 m-4 text-white display-3 text-center">Excluir</h1>
                    </main>

                    <form method="post">
                        {% csrf_token %}
                        Você tem certeza que quer excluir
                        o cliente <code>{{ cliente.nome }}</code>?
                        <br><br>
                        <button type="button" class="btn btn-outline-danger">
                            <a class="text-light" href="{% url 'client:lista_cliente' %}">
                                Cancelar
                            </a>
                        </button>
                        <button class="btn btn-danger">
                            Excluir
                        </button>
                    </form>
                </div>
            </div>
        </div>
    </div>
 </div>
{% endblock %}

pipenv install django-phonenumber-field[phonenumbers]

crud_project/client/templates/client/lista.html
{% extends 'base/base.html' %}
{% load static %}
{% load widget_tweaks %}
{% block title %}Lista de Clintes{% endblock title %}


{% block body %}

<div class="container">
    <div class="row">
         <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 mt-2">
             <div class="card">
                 <div class="card-body">
                     <h5 class="card-title">Lista de Clientes</h5>
                     {% if cliente|length > 0 %}
                         <p class="card-text">
                         Aqui está a lista de <code>Clientes</code>
                         cadastrados.
                         </p>
                         <table class="table">
                             <thead class="thead-dark">
                                 <tr>
                                     <th>ID</th>
                                     <th>Nome</th>
                                     <th>Endereço</th>
                                     <th>Data Nascimento</th>
                                     <th>Telefone</th>
                                 </tr>
                             </thead>
                             <tbody>
                                 {% for client in cliente %}
                                     <tr>
                                         <td>{{ client.id }}</td>
                                         <td><a href="{{ client.get_absolute_url }}"> {{ client.nome }} </a></td>
                                         <td>{{ client.endereco }}</td>
                                         <td>{{ client.data_nascimento }}</td>
                                         <td>{{ client.telefone }}</td>
                                         <td>
                                             <a href="{% url 'client:atualiza_cliente' slug=client.slug %}"
                                             class="btn btn-info">
                                             Atualizar
                                             </a>
                                             <a href="{% url 'client:deleta_cliente' slug=client.slug %}"
                                             class="btn btn-outline-danger">
                                             Excluir
                                            </a>
                                         </td>
                                     </tr>
                                 {% endfor %}
                             </tbody>
                         </table>
                     {% else %}
                            <div class="text-center mt-5 mb-5 jumbotron">
                                <h5>Nenhum <code>Cliente</code> cadastrado ainda.</h5>
                            </div>
                     {% endif %}
                     <hr />
                     <div class="text-right">
                        <a class="btn btn-primary"
                         href="{% url 'client:cadastra_cliente' %}">
                         Cadastrar Cliente
                        </a>
                     </div>
                 </div>
             </div>
         </div>
    </div>
</div>


{% endblock %}